# Stage 1: Build the Maven project
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
COPY . .
RUN mvn -B -DskipTests clean package

# Stage 2: Create the final Docker image
FROM adoptopenjdk/openjdk17:alpine-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
